### ISSUE TITLE
Build system enhancements

### ISSUE THREAD

**Issue by RostakaGmfun** [simple2d/simple2d#25]
Currently `simple2d` uses plain `Makefile`, which has some drawbacks:
* Tests are compiled with globally installed library and header file. This gives some pain during edit-compile-test cycle, as you have to issue `make`, `make install` and, eventually, `make tests`.
* `libsimple2d.a` is only updated with `make`, but existing object files are not replaced by new, so to have library reflect newest source code changes, you should first `make clean` and then `make`.
* `make install` does not rely on `libsimple2d.a` so it fails when there is no library file.

As an alternative way to overcome the problems stated above, I'd recommend to switch to `CMake` build system which is reliable and standardized. For RaspberryPi, it would be nice to have cross-compiling support.

**Comment by blacktm** [comment]
Yea, it sounds interesting. A central goal of this project is to make it easy for beginners, and those coming from other backgrounds like web development, to understand as many aspects of how this library works as possible. The simplicity of a Makefile makes it more accessible – all the commands are what actually gets run verbatim, nothing magical there. I passed over CMake a bit ago because I didn't see the benefits outweighing the added complexity. And also, after reading the intro [CMake tutorial](https://cmake.org/cmake-tutorial/) was promptly confused and gave up.

Now that this project is maturing and should demonstrate best practices, it's probably a good time to revisit. I'd definitely like to learn more about what it looks like to switch to CMake and the resulting experience for developers of the library and users of it.

**Comment by RostakaGmfun** [comment]
Well, writing `CMake` scripts may be a bit complicated for beginners, but using them is quite straightforward. The user should just create a build directory, cd in, invoke `cmake <path-to-project-root>` (e. g. `cmake ..`, if build directory is inside project root). Then voila! you have generated `Makefile`. Now you can `make`, `make clean`, `make install` easily.
And `CMake` can generate you build scripts for different platforms, compilers, IDEs, so it is easy to generate VisualStudio or Xcode projects.

**Comment by blacktm** [comment]
The makefiles (for `make` and `nmake`) are working pretty well for now, but I'm sure we'll return to this in the future as further needs arise.
