### ISSUE TITLE
Error compiling testcard demo on PocketCHIP

### ISSUE THREAD

**Issue by andrewhavens** [simple2d/simple2d#32]
Unfortunately, I ran into an error while trying to compile the testcard demo on my new [PocketCHIP](https://nextthing.co/).

```
cc testcard.c `simple2d --libs` -o testcard'
testcard.c:8:1: error: unknown type name 'S2D_Sprite'
 S2D_Sprite *spr;
 ^
testcard.c: In function 'main':
testcard.c:248:7: warning: assignment makes pointer from integer without a cast
   spr = S2D_CreateSprite("media/sprite_sheet.png");
       ^
testcard.c:249:6: error: request for member 'x' in something not a structure or union
   spr->x = 350;
      ^
testcard.c:250:6: error: request for member 'y' in something not a structure or union
   spr->y = 200;
      ^
```

I saw that issue #20 might be related.

**Comment by blacktm** [comment]
Ah, so when installing from the `simple2d.sh` script, it grabs the latest version, which is currently [v0.2.1](https://github.com/simple2d/simple2d/releases). Sprites were added after this release was cut (in https://github.com/simple2d/simple2d/commit/258b7446ec74ae88d7532f1593460b743e8f7861), and you're probably compiling the testcard from master, which has Sprite tests.

You could use the `simple2d install --edge` command to install at the latest commit from master, or I suppose I could get off my butt and cut a new release 😄. Since master is probably always going to include some breaking change ahead of the latest proper release, I'm interested to know how to make this more clear. Maybe it's as simple as stating such in the [Building and Running Tests](https://github.com/simple2d/simple2d#building-and-running-tests) section in the README, but people might skim and miss that. Let me know if you have ideas!

**Comment by andrewhavens** [comment]
Ah okay, makes sense. I just coped the code from master without thinking that it needed to match a specific version. I think this is a common issue for other open source projects as well. I suppose you could move unreleased code/docs to a development branch. Going to try installing "edge" and run the script again.

**Comment by andrewhavens** [comment]
Ran `simple2d install --edge`, tried to compile the testcard script, and I see this message:

```
$ cc testcard.c `simple2d --libs` -o testcard
//usr/local/lib/libsimple2d.a(gles.o): In function `S2D_GLES_DrawSprite':
gles.c:(.text+0x80e): undefined reference to `S2D_GL3_DrawTexture'
collect2: error: ld returned 1 exit status
```

**Comment by blacktm** [comment]
Dang it, got bit by my copy/paste coding. Should've been `S2D_GLES_DrawTexture`, not `GL3` there. Just fixed in https://github.com/simple2d/simple2d/commit/dd4b61e741aa7f0584eeafaf5ed478629878684f. If you reinstall using `simple2d install --edge`, should work now.

**Comment by blacktm** [comment]
I changed this to `simple2d install --HEAD` to make it consistent with how Homebrew works. Anyways, all this should be fixed.
