### ISSUE TITLE
lockup on Rpi 3 raspbian Jessie

### ISSUE THREAD

**Issue by n2ballroy** [simple2d/simple2d#44]
Sorry to put my trivial problem here, but I could not find another forum.
When I run the example such as triangle, I get the expected multi-color triangle with a black background covering the entire screen.  Unfortunately I cannot return back to the CLI (terminal).  My Rpi seems to be locked up.  The only anomalies I noticed on install were audio issues.

I installed via
git clone --recursive https://github.com/simple2d/simple2d.git per read.me instructions

Unsure how to debug this.  Any thoughts??

**Comment by blacktm** [comment]
Sorry for the delayed response. When using Linux + ARM platforms, the install script will disable X11 for performance reasons (like to enable hardware acceleration) and so that programs can run without a windowing environment at all. So the result is programs full screen, covering the whole desktop. The [`triangle.c` demo](https://github.com/simple2d/simple2d/blob/master/test/triangle.c) only draws that multi-color triangle and nothing else, like capturing input. On the Raspberry Pi, this makes it a little hard to quit the program. `Ctrl-C` might still work, but if focus leaves the terminal, commands might not be picked up. If you try running the `testcard.c` program, [`esc` will close the window](https://github.com/simple2d/simple2d/blob/master/test/testcard.c#L35). Bottom line, things are probably working as expected — I hope! Do let me know if you think the RPI really is hanging.

**Comment by blacktm** [comment]
Going to close for now, but will reopen if this is a confirmed issue.
