### ISSUE TITLE
Error: (SDL_Init) No avalible video device

### ISSUE THREAD

**Issue by Threadzless** [simple2d/simple2d#51]
I tried to use this library on my 9$ CHIP computer, and despite my best efforts I was unable to get further than SDL_Init without an error dropping. I followed the instructions for downloading and compiling from source using the git and make commands, and still no luck. Is there anything I can do to debug this problem or is it simply unresolvable?

**Comment by blacktm** [comment]
Hi there. I came across [your comment](https://bbs.nextthing.co/t/simple2d-error-sdl-init-no-available-video-device/16618) in the CHIP forums. If you just followed the instructions to install from source, you'll be missing a number of dependencies. Instead, first uninstall the `libsdl2-dev` and `libsdl2-ttf-dev` packages, then try following the [Linux instructions](https://github.com/simple2d/simple2d#on-linux) which use the install script. Note the comment below, "A note on Linux/ARM platforms," which states you'll have to use the install script since SDL needs to be configured specially for ARM/GLES platforms. Hope that helps!

**Comment by Threadzless** [comment]
I tried your suggestion on a fresh install (v4.4 Desktop with DIP support) by punching this into terminal emulator:
`sudo apt-get update`
`sudo apt-get purge libsdl2 libsdl2-ttf libsdl2-dev libsdl2-ttf-dev` 
`sudo apt-get install build-essential libfreetype6 libfreetype6-dev`
`url='https://raw.githubusercontent.com/simple2d/simple2d/master/bin/simple2d.sh'; which curl > /dev/null && cmd='curl -fsSL' || cmd='wget -qO -'; bash <($cmd $url) install`

The works fine for SDL2, SDL2_image, and SDL2_mixer but fails on SDL2_ttf:
`Makefile:474: recipe for target 'glfont' failed`
`make: *** [glfont] Error 1`
` `
`==> Checking for SDL2... yes`
`==> Checking for SDL2_image... yes`
`==> Checking for SDL2_mixer... yes`
`==> Checking for SDL2_ttf... no`
`Error: SDL libraries did not install correctly`

This is what pushed me to use the git make files in the first place

**Comment by blacktm** [comment]
The Simple 2D script has been updated to use the latest SDL libs. Hopefully this has been resolved, but if not, happy to continue investigating.
