### ISSUE TITLE
MinGW Build Error

### ISSUE THREAD

**Issue by ColinMcNeil** [simple2d/simple2d#62]
I had issues with SDL linking, but those have been resolved.
Currently I get these errors in every test.

`C:\Users\Colin\AppData\Local\Temp\ccWpinzd.o:test.c:(.text+0x8a): undefined reference to S2D_DrawTriangle`

`C:\Users\Colin\AppData\Local\Temp\ccWpinzd.o:test.c:(.text+0xcf): undefined reference to S2D_CreateWindow`

`C:\Users\Colin\AppData\Local\Temp\ccWpinzd.o:test.c:(.text+0xdf): undefined reference to `S2D_Show`

`C:\Users\Colin\AppData\Local\Temp\ccWpinzd.o:test.c:(.text+0xeb): undefined reference to S2D_FreeWindow'`

My local folder contains all of the files in the installer. and C:\MinGW\msys\1.0\local\include contains simple2d.h. I have no idea why it is not linking to the library. The file contains all the functions.

And `simple2d doctor` passes all tests.

**Comment by blacktm** [comment]
Huh, if it can't find references, then I'm guessing it might be a lib search path issue...? MinGW is a little weird, and I don't have a ton of experience with it (I only use it when testing [Ruby 2D on Windows](http://www.ruby2d.com/learn/windows/)). I found [this article](http://www.mingw.org/wiki/HOWTO_Specify_the_Location_of_Libraries_for_use_with_MinGW) which might help checking and modifying the library search paths. You might want to try explicitly compiling with `-L/usr/local/lib -lsimple2d`. Right now `simple2d --libs` just assumes `/usr/local/lib` is in your linker path, but if that's not guaranteed on MinGW, maybe we should change that and add the full path instead. Let me know what you find out, good luck!

**Comment by ColinMcNeil** [comment]
I have run this command and it gives the same error.
`g++ test.c -IC:/MinGW/msys/1.0/local/include -LC:/MinGW/msys/1.0/local/lib -lmingw32 -lsimple2d -lSDL2 -lSDL2_i
mage -lSDL2_mixer -lSDL2_ttf -lopengl32 -lglew32`

**Comment by blacktm** [comment]
Well, I'm stumped. Trying to think of thinks to try... 🤔
Does using `gcc` instead of `g++` make any difference? I'm guessing you downloaded the compiled MinGW libs from the [release notes](https://github.com/simple2d/simple2d/releases), yes? I'm wondering if something different, not portable. Maybe you could try cloning and [building this repo from source](https://github.com/simple2d/simple2d#building-from-source).

If none of that works, maybe I can follow the steps you used to set up your environment and try. Like I mentioned, I get MinGW via the [RubyInstaller](https://rubyinstaller.org), which is probably quite different than how others install a MinGW env.

**Comment by blacktm** [comment]
I think we're going to start recommending a [MSYS2](http://www.msys2.org) / MinGW environment, which I've been having more success with. Probably easiest way to get it is using [Chocolatey](https://chocolatey.org/packages/msys2) and then using the MinGW 64-bit command prompt (installed to `C:\tools\msys64\mingw64.exe`). And, we can now use the same [install script for Linux](https://github.com/simple2d/simple2d#on-linux) to get Simple 2D. Hope this helps!
