### ISSUE TITLE
Mouse coordinates on a Raspberry Pi are 0-to-4000 on a 800x480 screen

### ISSUE THREAD

**Issue by kjans** [simple2d/simple2d#66]
My application creates a 800x480 screen...
It receives mouse events properly when run on a Linux PC.
When I recompile and run on a Raspberry Pi the returned mouse 
coordinates are 0 to 3999...for both x and y.
This is also true when I run the "testcard" application.
Any ideas?

**Comment by blacktm** [comment]
Hi @kjans, that's very weird. I know there's been a few new releases to Raspbian since I lasted tested on the Pi. SDL 2.0.6 was also just released, which may have fixes. I'll try to find time in the next few days to update everything and test. Let me know if you discover something in the meantime. Thanks!

**Comment by blacktm** [comment]
I think this has been fixed with the latest version of SDL, which Simple 2D now installs.
