### ISSUE TITLE
Draw pixels

### ISSUE THREAD

**Issue by thomasb892** [simple2d/simple2d#80]
It would be good to add a DrawPixel function because anyways a DrawCircle or DrawEllipse and other such things won't be implemented(I'm guessing). So, I you must give user a little more flexiflbility by adding DrawPixel so that they can make on themselves and it won't be slow with OpenGL!

**Comment by thomasb892** [comment]
I will make lua bindings for your library and make it available to make people. Do you expect kids to make their games starting from c? I don't. Please enhance your library, I will porting this to lua and later on to python. Also can we use this for commercial purpose?

**Comment by blacktm** [comment]
Yea, I don't think we'll ever support vector graphics, [like Cairo](https://cairographics.org/samples), however, I do think it'd be helpful to provide [a generic `SDL_Surface`](https://wiki.libsdl.org/SDL_Surface) to draw pixels directly, render them as a GL texture as you suggest.

And no, I don't think everyone will make games in C (not even me 😬), which is why I'm also making [Ruby 2D](http://www.ruby2d.com). You can absolutely use it commercially — everything is [MIT licensed](https://github.com/simple2d/simple2d/blob/master/LICENSE.md) (maybe buy me a 🍺 if you make a million dollars though).

**Comment by thomasb892** [comment]
Would you like maintaining a luajit ffi port of simple2d (just like there is ruby 2D) patched by me? I would be very happy if someone could use this in future projects. I want to send you source code please provide your email. I will be porting to PyPy also very soon. This would increase the number of people using your library, also lua and python are frequently used for game development.

**Comment by thomasb892** [comment]
I'm actually porting this library primarily for my project. I don't want someone else to re invent the wheel as it takes a lot of time to learn to write modules, thanks a lot for writing this, I can't imagine if I you would'nt have then I had to take the trouble to write this whole thing. If our team is able to do what we desire successfully with this library, we will send you some beer.

**Comment by blacktm** [comment]
Painting pixels or creating custom textures programmatically is a really cool idea, but going to close this until we have a specific strategy or implementation in mind.
